feature-file: .fcoverage/feature-list.md
report-file: .fcoverage/report.md
prompts-directory: .fcoverage/prompts
vector-db-persist-location: .fcoverage/vdb

mongo-db-connection-string: mongodb://localhost:27017/
mongo-db-database: fcoverage-dummy

documents:
    - doc1.txt
    - doc2.txt

tests: tests
source: src

llm:
    model: gemini-2.0-flash
    provider: google_genai

embedding:
    model: models/gemini-embedding-exp-03-07
    provider: google_genai
