name: Acceptance Tests

on:
  issue_comment:
    types: [created]

jobs:
  run-tests:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'run acceptance tests')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run pytest and capture results
        id: run_tests
        env:
          GOOGLE_API_KEY= ${{ secrets.GOOGLE_API_KEY }}
        run: |
          set +e
          pytest tests/acceptance > result.log 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          echo "Test results:"
          tail -n 20 result.log
          echo "result<<EOF" >> $GITHUB_ENV
          head -n 20 result.log >> $GITHUB_ENV
          echo "..." >> $GITHUB_ENV
          tail -n 20 result.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR with results
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          COMMENT="✅ **Test Results** for 'run tests':\n\n\`\`\`\n${{ env.result }}\n\`\`\`\n[🔗 View Full Logs]($RUN_URL)"
          gh pr comment ${{ github.event.issue.number }} --body "$COMMENT"
