name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run pytest
      run: |
        pwd
        env
        ls -la
        ls -la tests
        pytest -v tests/

    - name: Archive e2e tests result files
      uses: actions/upload-artifact@v4
      with:
        name: e2e_test_artifacts
        path: test_artifacts/
